# Site settings
title: SKINHEAD
header-img: img/home-bg.jpg
email: yahuoking@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://blog.yahuo.info"
twitter_username: yahuo
github_username:  yahuo
facebook_username:  yahuoking
weibo_username: moushayiciyahuo
author: Jinxin

production_url: "blog.yahuo.info"

# Build settings
highlighter: pygments
markdown: redcarpet  # [ maruku | rdiscount | kramdown | redcarpet ]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
redcarpet:
  extensions:
    ["fenced_code_blocks",
    "no_intra_emphasis",
    "strikethrough",
    "no_intra_emphasis",
    "autolink",
    "tables",
    "with_toc_data"]

# kramdown:
#   input:            GFM
#   auto_id_prefix:   ''
#   auto_ids:         true
#   extensions:
#     - autolink
#     - footnotes
#     - smart
  # transliterated_header_ids: false
  # footnote_nr:   1
  # entity_output: as_char
  # toc_levels:    1..6
  # smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
